# Testing notebook for RoBERTa converter

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/omkar-334/keras-scripts/blob/main/RoBERTa_converter.ipynb)

# Installs and Imports

In [1]:
!git clone --branch roberta https://github.com/omkar-334/keras-hub.git
%cd keras-hub
!pip install -r requirements.txt -q

Cloning into 'keras-hub'...
remote: Enumerating objects: 17390, done.
remote: Counting objects: 100% (320/320), done.
remote: Compressing objects: 100% (209/209), done.
remote: Total 17390 (delta 202), reused 113 (delta 111), pack-reused 17070 (from 3)
Receiving objects: 100% (17390/17390), 7.01 MiB | 14.06 MiB/s, done.
Resolving deltas: 100% (13952/13952), done.
/content/keras-hub
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 230.2/230.2 MB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.7/178.7 MB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 53.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 220.6/220.6 kB 11.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.2/11.2 MB 54.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.0/241.0 kB 15.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━

In [ ]:
# This is needed if the model is gated or restricted.
!huggingface-cli login


    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

    To log in, `huggingface_hub` requires a token generated from https://huggingface.co/settings/tokens .
Enter your token (input will not be visible): 
Add token as git credential? (Y/n) n
Token is valid (permission: read).
The token `keras-contribs` has been saved to /root/.cache/huggingface/stored_tokens
Your token has been saved to /root/.cache/huggingface/token
Login successful.
The current active token is: `keras-cont

In [3]:
import numpy as np
import torch
import tensorflow as tf
from transformers import AutoModel, AutoTokenizer

 # Load HF Model and Tokenizer

In [4]:
from transformers import RobertaTokenizer, TFRobertaModel
import tensorflow as tf

hf_model = TFRobertaModel.from_pretrained("roberta-base")
tokenizer = RobertaTokenizer.from_pretrained("roberta-base")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFRobertaModel: ['lm_head.dense.weight', 'roberta.embeddings.position_ids', 'lm_head.layer_norm.weight', 'lm_head.dense.bias', 'lm_head.bias', 'lm_head.layer_norm.bias']
- This IS expected if you are initializing TFRobertaModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFRobertaModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
Some weights or buffers of the TF 2.0 model TFRobertaModel were not initialized from the PyTorch model and are newly initialized: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and infe

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [5]:
text = "Hello, how are you?"

inputs = tokenizer(text, return_tensors="tf", padding=True, truncation=True)

hf_output = hf_model(**inputs).last_hidden_state

# Load Keras Model

In [7]:
import keras_hub
model = keras_hub.models.RobertaBackbone.from_preset("hf://FacebookAI/roberta-base", dtype="bfloat16")

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

In [8]:
model.summary()

Model: "roberta_backbone"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ token_ids (InputLayer)    │ (None, None)           │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ embeddings                │ (None, None, 768)      │     38,996,736 │ token_ids[0][0]        │
│ (TokenAndPositionEmbeddi… │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ embeddings_layer_norm     │ (None, None, 768)      │          1,536 │ embeddings[0][0]       │
│ (LayerNormalization)      │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ embeddings_dropout        │ (None, None, 768)      │              0 │ embeddings_layer_norm… │
│ (Dropout)                 │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ padding_mask (InputLayer) │ (None, None)           │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ transformer_layer_0       │ (None, None, 768)      │      7,087,872 │ embeddings_dropout[0]… │
│ (TransformerEncoder)      │                        │                │ padding_mask[0][0]     │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ transformer_layer_1       │ (None, None, 768)      │      7,087,872 │ transformer_layer_0[0… │
│ (TransformerEncoder)      │                        │                │ padding_mask[0][0]     │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ transformer_layer_2       │ (None, None, 768)      │      7,087,872 │ transformer_layer_1[0… │
│ (TransformerEncoder)      │                        │                │ padding_mask[0][0]     │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ transformer_layer_3       │ (None, None, 768)      │      7,087,872 │ transformer_layer_2[0… │
│ (TransformerEncoder)      │                        │                │ padding_mask[0][0]     │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ transformer_layer_4       │ (None, None, 768)      │      7,087,872 │ transformer_layer_3[0… │
│ (TransformerEncoder)      │                        │                │ padding_mask[0][0]     │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ transformer_layer_5       │ (None, None, 768)      │      7,087,872 │ transformer_layer_4[0… │
│ (TransformerEncoder)      │                        │                │ padding_mask[0][0]     │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ transformer_layer_6       │ (None, None, 768)      │      7,087,872 │ transformer_layer_5[0… │
│ (TransformerEncoder)      │                        │                │ padding_mask[0][0]     │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ transformer_layer_7       │ (None, None, 768)      │      7,087,872 │ transformer_layer_6[0… │
│ (TransformerEncoder)      │                        │                │ padding_mask[0][0]     │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ transformer_layer_8       │ (None, None, 768)      │      7,087,872 │ transformer_layer_7[0… │
│ (TransformerEncoder) 

 Total params: 124,052,736 (236.61 MB)

 Trainable params: 124,052,736 (236.61 MB)

 Non-trainable params: 0 (0.00 B)

In [9]:
keras_inputs = {
    "token_ids": inputs["input_ids"].numpy(),  # Token IDs
    "padding_mask": inputs["attention_mask"].numpy(),  # Padding Mask
}

keras_output = model(keras_inputs)

# Check shapes and outputs

In [10]:
print(hf_output.shape)
print(keras_output.shape)

(1, 8, 768)
(1, 8, 768)


In [13]:
print("Huggingface output\n", hf_output)
print("\nKeras output\n", keras_output)

Huggingface output
 tf.Tensor(
[[[-0.06098359  0.1249077  -0.01024088 ... -0.05549887 -0.05278057
   -0.02032275]
  [-0.33764884  0.20138168  0.0747247  ...  0.16684791  0.02431505
   -0.13936536]
  [-0.0294365   0.23096952  0.18173099 ... -0.146936   -0.05403062
   -0.02496257]
  ...
  [-0.11631885  0.2576877   0.08946906 ... -0.0149455   0.07766248
    0.03402064]
  [-0.07787552  0.26423284  0.4469964  ... -0.76866114  0.02005992
    0.0730704 ]
  [-0.05071665  0.14344667 -0.03572285 ... -0.10117419 -0.05277739
   -0.05274257]]], shape=(1, 8, 768), dtype=float32)

Keras output
 tf.Tensor(
[[[-0.0717773 0.11084 -0.000291824 ... -0.0913086 -0.0463867 -0.0290527]
  [-0.0178223 0.0791016 0.106445 ... -0.283203 -0.0174561 0.0490723]
  [-0.0717773 0.111328 0.000850677 ... -0.0898438 -0.0456543 -0.0284424]
  ...
  [-0.0354004 0.203125 0.00379944 ... 0.0693359 -0.00118256 0.0446777]
  [0.020752 0.164062 0.316406 ... -0.511719 0.0356445 0.0737305]
  [-0.0668945 0.125977 -0.0184326 ... -0.1376

In [23]:
import numpy as np

np.testing.assert_allclose(
    tf.cast(keras_output, dtype=tf.float32),
    tf.cast(hf_output, dtype=tf.float32),
    atol=1e-5
    )

AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-05

Mismatched elements: 6142 / 6144 (100%)
Max absolute difference: 6.7898917
Max relative difference: 1783.8203
 x: array([[[-7.177734e-02,  1.108398e-01, -2.918243e-04, ...,
         -9.130859e-02, -4.638672e-02, -2.905273e-02],
        [-1.782227e-02,  7.910156e-02,  1.064453e-01, ...,...
 y: array([[[-0.060984,  0.124908, -0.010241, ..., -0.055499, -0.052781,
         -0.020323],
        [-0.337649,  0.201382,  0.074725, ...,  0.166848,  0.024315,...

# Load Keras RoBERTa Tokenizer

In [34]:
import subprocess

def find_file(filename):
    try:
        path = subprocess.check_output(f'find /root/.cache/huggingface -name {filename}', shell=True, text=True).strip()
        if path:
            return path.split("\n")[0]
        else:
            raise FileNotFoundError(f"{filename} not found!")
    except subprocess.CalledProcessError:
        raise FileNotFoundError(f"Error finding {filename}!")

In [35]:
from transformers import RobertaTokenizer
from keras_hub.tokenizers import RobertaTokenizer as KerasRobertaTokenizer


vocab_path = find_file("vocab.json")
merges_path = find_file("merges.txt")

keras_tokenizer = KerasRobertaTokenizer(vocabulary=vocab_path, merges=merges_path)

# Test tokenizer outputs

In [37]:
text = "RoBERTa is a transformers model pretrained on a large corpus."

hf_tokens = hf_tokenizer.encode(text)
keras_tokens = keras_tokenizer.tokenize(text)

print("Hugging Face Tokenizer Output:\n", hf_tokens)
print("\nKeras Tokenizer Output:\n", keras_tokens)

Hugging Face Tokenizer Output:
 [0, 27110, 11126, 38495, 16, 10, 7891, 268, 1421, 11857, 26492, 15, 10, 739, 42168, 4, 2]

Keras Tokenizer Output:
 tf.Tensor(
[27110 11126 38495    16    10  7891   268  1421 11857 26492    15    10
   739 42168     4], shape=(15,), dtype=int32)


Here, the Keras Tokenizer output is missing 2 tokens - [0] and [2] , at the start and the end respectively. These tokens denote [CLS] and [SEP]
